name = "Basis_OOP"
version = "0.0.0"
license = "MIT"
author = "David Lauvergnat"
maintainer = "david.lauvergnat@universite-paris-saclay.fr"
copyright = "2024 David Lauvergnat"

[library]
source-dir="SRC"

[[executable]]
name="Exe"
source-dir="APP"
main="Exa_QDBa.f90"


[build]
link = ["blas", "lapack"]

[dependencies]
QDUtilLib = { git = "https://github.com/lauvergn/QDUtilLib" }