#!/bin/bash

#remove le link
rm -f AD_dnSVM QDUtilLib

for dirlib in *_loc
do
  echo $dirlib
  cd $dirlib
  make --silent cleanall &> /dev/null
  test -d Ext_lib && rm -rf Ext_lib/Save*.zip *_loc .git
  cd ..
done

